import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [todo, setTodo] = useState<string>("");
  const [todos, setTodos] = useState<string[]>([]);

  const addTodo = (e: any) => {
    if (todo !== "") {
      if (e.key === "Enter") {
        setTodos([...todos, todo]);
        setTodo("");
      }
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Todo Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>todos</h1>
        <input
          type="text"
          name="todo"
          value={todo}
          className={styles.input}
          placeholder="What needs to be done?"
          onChange={(event) => {
            setTodo(event.target.value);
          }}
          onKeyDown={addTodo}
        />
        <div className={styles.toggleAllContainer}>
          <input className={styles.toggleAll}></input>
          <label></label>
        </div>

        <ul className={styles.todoContainer}>
          {todos.map((todo, index) => (
            <div key={index} className={styles.toggleWrapper}>
              <input className={styles.toggle} type="checkbox" ></input>
              <li className={styles.todoWrapper} key={index}>
                {todo}
              </li>
            </div>
          ))}
          {todos.length > 0 ? (
            <div className={styles.filtersContainer}>
              <span className={styles.todoCount}>
                {todos.length} items left
              </span>
              <ul className={styles.filters}>
                <a className="filter">All</a>
                <a>Active</a>
                <a>Completed</a>
              </ul>
            </div>
          ) : null}
        </ul>
      </main>

      <footer className={styles.footer}>
        <p>Double-click to edit a todo</p>
        <div>
          <p>
            Created by{" "}
            <a href="https://github.com/KaterinaSlobodchikova">katerinasl</a>
          </p>
        </div>

        <div>
          <p>
            Part of <a href="https://todomvc.com/">TodoMVC</a>{" "}
          </p>
        </div>
      </footer>
    </div>
  );
}
