import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [todo, setTodo] = useState<string>("");
  const [todos, setTodos] = useState<any[]>([]);
  const [completedTodoCount, setCompletedTodoCount] = useState(0);
  const [checked, setChecked] = useState(false);

  const addTodo = (e: any) => {
    if (todo !== "") {
      if (e.key === "Enter") {
        const id = todos.length + 1;
        setTodos((prev) => [
          ...prev,
          {
            id: id,
            task: todo,
            complete: false,
          },
        ]);
        setTodo("");
      }
    }
  };

  const handleChange = () => {
    setChecked(!checked);
  };

  const handleComplete = (id: number) => {
    let list = todos.map((task) => {
      let item = {};
      if (task.id == id) {
        if (!task.complete) {
          setCompletedTodoCount(completedTodoCount + 1);
        } else {
          setCompletedTodoCount(completedTodoCount - 1);
        }
        item = { ...task, complete: !task.complete };
      } else item = { ...task };
      return item;
    });
    setTodos(list);
  };

  const deleteTodo = (text: string) => {
    const newTodos = todos.filter((todo) => {
      return todo !== text;
    });
    setTodos(newTodos);
  };

  const getCompleted = () => {
    let filtered = todos.filter((task) => {
      return !task.complete;
    });
    setTodos(filtered);
  };

  const getActive = () => {
    let filtered = todos.filter((task) => {
      return task.complete == true;
    });
    setTodos(filtered);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Todo Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>todos</h1>
        <input
          type="text"
          name="todo"
          value={todo}
          className={styles.input}
          placeholder="What needs to be done?"
          onChange={(event) => {
            setTodo(event.target.value);
          }}
          onKeyDown={addTodo}
        />
        <ul className={styles.todoContainer}>
          {todos.map((todo) => {
            return (
              <div key={todo.id} className={styles.toggleWrapper}>
                <label className={styles.checkboxContainer}>
                  <input
                    className={styles.toggle}
                    type="checkbox"
                    onClick={() => handleChange}
                  ></input>
                  <span
                    className={styles.checkmark}
                    onClick={() => handleComplete(todo.id)}
                    style={{
                      textDecoration: todo.complete && "line-through",
                    }}
                  ></span>
                </label>

                <li
                  className={styles.todoWrapper}
                  key={todo.id}
                  style={{
                    textDecoration: todo.complete && "line-through",
                    color: todo.complete && "#d9d9d9",
                  }}
                >
                  {todo.task}
                </li>

                <button
                  className={styles.deleteBtn}
                  onClick={() => {
                    deleteTodo(todo);
                  }}
                >
                  x
                </button>
              </div>
            );
          })}
          {todos.length > 0 ? (
            <div className={styles.filtersContainer}>
              <div className={styles.infoContainer}>
                <span className={styles.todoCount}>
                {todos.length - completedTodoCount} items left
              </span>
              <ul className={styles.filters}>
                <a className="filter">All</a>
                <a>Active</a>
                <a>Completed</a>
              </ul>
              </div>
              <div>
                {completedTodoCount ? (<button className={styles.btnClear} onClick={getCompleted}>
                Clear completed
              </button>) : null}
              </div>
              
              </div>
          ) : null}
        </ul>
      </main>

      <footer className={styles.footer}>
        <p>Double-click to edit a todo</p>
        <div>
          <p>
            Created by{" "}
            <a href="https://github.com/KaterinaSlobodchikova">katerinasl</a>
          </p>
        </div>

        <div>
          <p>
            Part of <a href="https://todomvc.com/">TodoMVC</a>{" "}
          </p>
        </div>
      </footer>
    </div>
  );
}
